### ISSUE TITLE
Test exception in constructor

### ISSUE THREAD

**Issue by srph** [CoreProc/msisdn-ph-php#5]
Not sure how to mock a static method lol

**Comment by chrisbjr** [comment]
Nice kier. Thanks. I guess you can assertInstance exception. You can try it if you want.

**Comment by srph** [comment]
To elaborate, I'd like to stub `Msisdn::validate` to isolate the _exception_. [#L24](https://github.com/CoreProc/msisdn-ph-php/blob/ae690e2a4c435eddb5653e1432e594886add66a6/src/Msisdn.php#L24)

I'm checking PHPUnit and Mockery, and there doesn't seem to be a way with the latest versions. Features to stub a static method were opted out of PHPUnit.

From what I've understood from reading the docs a while ago, we got a bad pattern in the library.

Perhaps we can just rid of the _static_ method, and refactor `validate` be a _protected_ instance method (although it may seem a bit unsemantic).

These are just suggestions :smile:. I'm not very familiar with PHPUnit, so I'm probably blabbing stuff I don't know about :laughing:.

cc @awkwardusername :tada:

**Comment by chrisbjr** [comment]
The convenience of having the `validate` method as static is so you can validate mobile number without having to instantiate the class.

I'm pushing a commit to test for the exception.

**Comment by srph** [comment]
Not a big deal, but I really don't like this non-isolated tests. Nice work, though :tada:
